name: Deploy to Kind with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Changed from ubuntu-latest to self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Deploy Helm charts
        run: |
          for chart in ./helm/*/; do
            if [ -d "$chart" ]; then
              chart_name=$(basename "$chart")
              echo "Deploying chart: $chart_name"
              helm upgrade --install $chart_name $chart --create-namespace --namespace $chart_name
            fi
          done