name: Deploy Helm Chart Locally

on:
  workflow_dispatch:
    inputs:
      chart_version:
        description: 'Helm chart version to use (e.g., 0.1.0)'
        required: true
      app_image_tag:
        description: 'App Docker image tag (e.g., 1.17.0)'
        required: true
      release_name:
        description: 'Helm release name'
        required: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Deployment Variables
        run: |
          CHART_PATH="./helm/sample-app"
          echo "CHART_PATH=$CHART_PATH" >> $GITHUB_ENV
          echo "RELEASE_NAME=${{ github.event.inputs.release_name }}" >> $GITHUB_ENV
          echo "CHART_VERSION=${{ github.event.inputs.chart_version }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.inputs.app_image_tag }}" >> $GITHUB_ENV

      - name: Verify Helm Chart Exists
        run: |
          if [ ! -d "$CHART_PATH" ]; then
            echo "Error: Helm chart directory not found at $CHART_PATH!"
            exit 1
          fi
          if [ ! -f "$CHART_PATH/values.yaml" ]; then
            echo "Error: values.yaml not found in $CHART_PATH!"
            exit 1
          fi

      - name: Update values.yaml with Chart Version and Image Tag
        run: |
          yq e ".version = \"$CHART_VERSION\"" -i "$CHART_PATH/values.yaml"
          yq e ".image.tag = \"$IMAGE_TAG\"" -i "$CHART_PATH/values.yaml"
          echo "Updated values.yaml:" 
          cat "$CHART_PATH/values.yaml"

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace default \
            --version $CHART_VERSION \
            -f "$CHART_PATH/values.yaml"

      - name: Verify Deployment
        run: |
          helm list --namespace default
