name: Deploy to Kind with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Kind
        run: |
          go install sigs.k8s.io/kind@latest
          kind create cluster

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          kind get kubeconfig > $HOME/.kube/config
          kubectl cluster-info

      - name: Deploy Helm charts
        run: |
          for chart in ./helm/*/; do
            if [ -d "$chart" ]; then
              chart_name=$(basename "$chart")
              echo "Deploying chart: $chart_name"
              helm upgrade --install $chart_name $chart --create-namespace --namespace $chart_name
            fi
          done

