name: Deploy to Kind with Helm

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action: upgrade or rollback'
        required: true
        default: 'upgrade'
        type: choice
        options:
          - upgrade
          - rollback
      environment:
        description: 'Deployment environment (e.g., dev, staging, prod)'
        required: true
      chart_version:
        description: 'Helm chart version to use (e.g., 0.1.0)'
        required: true
      app_image_tag:
        description: 'App Docker image tag (e.g., 1.17.0)'
        required: true
      revision:
        description: 'Revision number (required for rollback)'
        required: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Deployment Variables
        run: |
          RELEASE_NAME="${{ github.event.inputs.environment }}-sample-app"
          NAMESPACE="${{ github.event.inputs.environment }}"
          CHART_PATH="./helm/sample-app"
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          echo "CHART_PATH=$CHART_PATH" >> $GITHUB_ENV

      - name: Update image tag in values.yaml
        run: |
          yq e ".image.tag = \"${{ github.event.inputs.app_image_tag }}\"" -i "$CHART_PATH/values.yaml"

      - name: Execute Helm Action
        run: |
          if [ "${{ github.event.inputs.action }}" == "upgrade" ]; then
            helm upgrade --install $RELEASE_NAME $CHART_PATH \
              --create-namespace --namespace $NAMESPACE \
              --version "${{ github.event.inputs.chart_version }}" \
              -f "$CHART_PATH/values.yaml"
          elif [ "${{ github.event.inputs.action }}" == "rollback" ]; then
            if [ -z "${{ github.event.inputs.revision }}" ]; then
              echo "Error: Revision must be specified for rollback"
              exit 1
            fi
            helm rollback $RELEASE_NAME "${{ github.event.inputs.revision }}"
          fi
